app_gen_region_api:
    resource: "@AppBundle/Controller/GenRegionRESTController.php"
    type:   rest
    prefix:   /api

app_user_api:
    resource: "@AppBundle/Controller/UserRESTController.php"
    type:   rest
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

lista_sector:
    path:     /lista_sector
    defaults: { _controller: AppBundle:GenRegionREST:listaSector }